name: obrp_scoe
channels:
  - conda-forge
dependencies:
  - python=3.9.12
  - pandas=1.1.3
  - openpyxl
  - bokeh
  - xlwt
  - ipython
  - nb_conda
  - seaborn
  - pip
  - jupyterlab
  - pip:
    - neurio
    - solaredge
    - SQLAlchemy
    - pymongo

